package com.example.demo.Repository.Entities;
// Generated Mar 5, 2023, 5:09:22 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrderProductsId generated by hbm2java
 */
@Embeddable
public class OrderProductsId  implements java.io.Serializable {


     private int orderDetailsId;
     private int productId;

    public OrderProductsId() {
    }

    public OrderProductsId(int orderDetailsId, int productId) {
       this.orderDetailsId = orderDetailsId;
       this.productId = productId;
    }
   


    @Column(name="order_details_id", nullable=false)
    public int getOrderDetailsId() {
        return this.orderDetailsId;
    }
    
    public void setOrderDetailsId(int orderDetailsId) {
        this.orderDetailsId = orderDetailsId;
    }


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderProductsId) ) return false;
		 OrderProductsId castOther = ( OrderProductsId ) other; 
         
		 return (this.getOrderDetailsId()==castOther.getOrderDetailsId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderDetailsId();
         result = 37 * result + this.getProductId();
         return result;
   }   


}


