package com.example.demo.Repository.Entities;
// Generated Mar 5, 2023, 5:09:22 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="flamingoo"
    , uniqueConstraints = @UniqueConstraint(columnNames="username") 
)
public class User  implements java.io.Serializable {


     private int id;
     private String username;
     private String password;
     private String firstName;
     private String lastName;
     private String gender;
     private String email;
     private String phone;
     private byte isAdmin;
     private String adrdressStreetName;
     private String adrdressCitytName;
     private String adrdressCountryName;
     private Set<UserReviewProduct> userReviewProducts = new HashSet<UserReviewProduct>(0);
     private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

    public User() {
    }

	
    public User(String username, String password, String firstName, String lastName, String gender, String email, String phone) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.email = email;
        this.phone = phone;
    }
    public User( String username, String password, String firstName, String lastName, String gender, String email, String phone, String adrdressStreetName, String adrdressCitytName, String adrdressCountryName, Set<UserReviewProduct> userReviewProducts, Set<OrderDetails> orderDetailses) {
       this.username = username;
       this.password = password;
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.email = email;
       this.phone = phone;
       this.adrdressStreetName = adrdressStreetName;
       this.adrdressCitytName = adrdressCitytName;
       this.adrdressCountryName = adrdressCountryName;
       this.userReviewProducts = userReviewProducts;
       this.orderDetailses = orderDetailses;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="first_name", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="gender", nullable=false, length=45)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", nullable=false, length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="isAdmin", nullable=false)
    public byte getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(byte isAdmin) {
        this.isAdmin = isAdmin;
    }

    
    @Column(name="adrdress_street_name", length=45)
    public String getAdrdressStreetName() {
        return this.adrdressStreetName;
    }
    
    public void setAdrdressStreetName(String adrdressStreetName) {
        this.adrdressStreetName = adrdressStreetName;
    }

    
    @Column(name="adrdress_cityt_name", length=45)
    public String getAdrdressCitytName() {
        return this.adrdressCitytName;
    }
    
    public void setAdrdressCitytName(String adrdressCitytName) {
        this.adrdressCitytName = adrdressCitytName;
    }

    
    @Column(name="adrdress_country_name", length=45)
    public String getAdrdressCountryName() {
        return this.adrdressCountryName;
    }
    
    public void setAdrdressCountryName(String adrdressCountryName) {
        this.adrdressCountryName = adrdressCountryName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserReviewProduct> getUserReviewProducts() {
        return this.userReviewProducts;
    }
    
    public void setUserReviewProducts(Set<UserReviewProduct> userReviewProducts) {
        this.userReviewProducts = userReviewProducts;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<OrderDetails> getOrderDetailses() {
        return this.orderDetailses;
    }
    
    public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
        this.orderDetailses = orderDetailses;
    }




}


