package com.example.demo.Repository.Entities;
// Generated Mar 5, 2023, 5:09:22 PM by Hibernate Tools 6.2.0.CR1


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * UserReviewProduct generated by hbm2java
 */
@Entity
@Table(name="user_review_product"
    ,catalog="flamingoo"
)
public class UserReviewProduct  implements java.io.Serializable {


     private UserReviewProductId id;
     private Product product;
     private User user;
     private Short reviewRating;
     private String reviewDescription;

    public UserReviewProduct() {
    }

	
    public UserReviewProduct(UserReviewProductId id, Product product, User user) {
        this.id = id;
        this.product = product;
        this.user = user;
    }
    public UserReviewProduct(UserReviewProductId id, Product product, User user, Short reviewRating, String reviewDescription) {
       this.id = id;
       this.product = product;
       this.user = user;
       this.reviewRating = reviewRating;
       this.reviewDescription = reviewDescription;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="user_id", nullable=false) ) } )
    public UserReviewProductId getId() {
        return this.id;
    }
    
    public void setId(UserReviewProductId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="review_rating")
    public Short getReviewRating() {
        return this.reviewRating;
    }
    
    public void setReviewRating(Short reviewRating) {
        this.reviewRating = reviewRating;
    }

    
    @Column(name="review_description", length=45)
    public String getReviewDescription() {
        return this.reviewDescription;
    }
    
    public void setReviewDescription(String reviewDescription) {
        this.reviewDescription = reviewDescription;
    }




}


